### ISSUE TITLE
[General workload issue]: While upgrading AMBA to latest version I'm seeing Non-Compliant resources for VM, Connectivity and Notification Policies.

### ISSUE THREAD

**Issue by mgirishk** [Azure/azure-monitor-baseline-alerts#630]
### Check for previous/existing GitHub issues

- [x] I have checked for previous/existing GitHub issues

### Issue Type?

Feature Request

### Description

<img width="774" alt="Image" src="https://github.com/user-attachments/assets/cd17c6f0-ba93-4a04-8843-86e35e710a40" />

<img width="815" alt="Image" src="https://github.com/user-attachments/assets/18b15ac8-ad2c-41d0-b803-157f175e884a" />

<img width="193" alt="Image" src="https://github.com/user-attachments/assets/682386c4-db40-4cd2-be41-1ade631c8eba" />

**Comment by colin-domansky** [comment]
@mgirishk Also seeing a similar issue

@Brunoga-MS, please review the compliance output, specifically current / target value for both these alerts which are failing to deploy.  They seem to be reversed.  

![Image](https://github.com/user-attachments/assets/feaaf13f-e6f7-4e6e-9167-2bd526c2a7a6)

![Image](https://github.com/user-attachments/assets/74ad8d2d-135c-4f62-bd75-e74d3f2cc8e5)

![Image](https://github.com/user-attachments/assets/03b0196d-2829-4962-9b5d-a7924596f38b)

**Comment by colin-domansky** [comment]
- The ALZ pattern has been previously deployed using the AVD/ALZ solution, within a separate repo.  
- I have deployed another versions of AMBA since yesterday (both 12.0 and 12.2.2 to see if there was a difference, there wasn't).  
- I have completed the remediation tasks a few times today and can confirm that I am still getting the same errors
- To add on, there are several other policy deployment errors, which I haven't yet posted about.  @Brunoga-MS should I add the errors here?

**Comment by mgirishk** [comment]
@Brunoga-MS I have tried to remediate and still getting same error.

**Comment by colin-domansky** [comment]
@Brunoga-MS I redeployed the environment the environment following your instructions above (to remove) while following the custom architecture example instructions.   Here are some errors pulled after a few remediations today.  

Hopefully this helps

![Image](https://github.com/user-attachments/assets/60ff3dee-473b-42ee-944e-2a2bb088e47d)

![Image](https://github.com/user-attachments/assets/0447ade4-1173-4aa3-809c-11a7a53ad3b5)

![Image](https://github.com/user-attachments/assets/a8811cdc-2b39-4b14-8db0-ff578470a9c7)

**Comment by Brunoga-MS** [comment]
@colin-domansky I think I found the problem ... There is a wrong default value for managed identity that is used during the remediation task and does not have the necessary rights. I am working on a fix that will be released soon.
@mgirishk : your issue should be now resolved. The latest code is available at both **_main_** and **_2025-06-03-hotfix_** branches

**Comment by colin-domansky** [comment]
@Brunoga-MS I'll have to wait for these good changes when the ALZ-AMBA library is automatically updated

**Comment by Brunoga-MS** [comment]
@colin-domansky yes please, we are working to get the changes in prod ASAP

**Comment by Brunoga-MS** [comment]
This is now resolved in TF deployment as well. ensure you are pointing to the latest TF library which is 2025.07.0

**Comment by Brunoga-MS** [comment]
@mgirishk : yes pls :)
